version: '3.7'
services:
 mysqldb:
  restart: always
  image: 'mariadb:10.4'
  container_name: gemsansar_db
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: gem_sansar

